sudo: required
dist: xenial

language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    update: true
    packages:
    - cmake
    - lua5.1
    - lua5.1-dev
    - libgraphviz-dev
    - qtbase5-dev
    - qtdeclarative5-dev
    - qtdeclarative5-qtquick2-plugin
    - qtdeclarative5-window-plugin
    - qtdeclarative5-controls-plugin
    - qtdeclarative5-dialogs-plugin
    - swig
    - python3
    - python3-dev

  homebrew:
    update: true
    packages:
    - cmake
    - lua51
    - qt
    - graphviz
    - swig
    - python

os:
  - linux
  - osx

env:
  global:
    - CTEST_OUTPUT_ON_FAILURE=1
  matrix:
    - TRAVIS_BUILD_TYPE=Debug
    - TRAVIS_BUILD_TYPE=Release


before_script:

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH=/usr/local/opt/qt5/bin:$PATH; fi
  - lua5.1 -v
  - swig -version
  - python3 --version
  - qmake --version
  - cmake --version
  # install robot-testing framework
  - git clone --depth=1 --branch master https://github.com/robotology/robot-testing-framework
  - cd robot-testing-framework
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DENABLE_LUA_PLUGIN:BOOL=ON -DENABLE_WEB_LISTENER:BOOL=ON ..
  - make
  - sudo make install
  - cd ../..

script:
  # configure rfsmTools
  - mkdir build
  - cd build
  - cmake -DLIBRFSM_USES_PYTHON=ON -DBUILD_TESTING=ON ..
  - make
  - ctest --output-on-failure --build . -C ${TRAVIS_BUILD_TYPE}
  - sudo make install

notifications:
  email:
    - nicolo.genesio@iit.it
